  - name: "Set min_free_kbytes to 1.1G"
    ansible.builtin.shell: |
        echo 3 > /proc/sys/vm/drop_caches
        echo 1310720 > /proc/sys/vm/min_free_kbytes
        echo "vm.min_free_kbytes=1310720" >> /etc/sysctl.conf
        done
    result: min_free_kbytes

  - name: "Disable THP"
    ansible.builtin.shell: |
      cat << 'EOF' > /etc/systemd/system/disable-transparent-huge-pages.service
      [Unit]
      Description=Disable Transparent Huge Pages

      [Service]
      Type=oneshot
      ExecStart=/bin/bash /etc/init.d/disable-transparent-hugepages start

      [Install]
      WantedBy=multi-user.target
      EOF
      done

  - name: "daemon reload and start"
    ansible.builtin.systemd:
      daemon_reload: true
      name: disable-transparent-huge-pages.service
      enabled: true
      state: started
