# zip.yml
---
- hosts: web1
  tasks:
    - name: Archive a Directory and Store in /root
      archive:
        path: /opt
        format: 'zip'
        dest: /root/opt.zip

# local.yml
---
- hosts: web1
  tasks: 
    - name: Unarchive a Directory and Store on web1
      unarchive:
        src: /home/thor/playbooks/local.zip
        dest: /tmp/

# data.yml
---
- hosts: web1
  tasks:
    - name: Extract data.tar.gz to /srv
      unarchive:
        src: /root/data.tar.gz
        dest: /srv
        remote_src: yes
    
    - name: Remove /root/data.tar.gz
      file: 
        path: /root/data.tar.gz
        state: absent

# download.yml
---
- hosts: web1
  tasks:
    - name: Download from Link and extract to /root
      unarchive:
        src: https://github.com/kodekloudhub/Hello-World/archive/master.zip
        dest: /root
        remote_src: yes

# files.yml
---
- hosts: web1
  tasks:
    - name: Create Tar ball for these files
      archive:
        src:
          - /root/file1.txt
          - /usr/local/share/file2.txt
          - /var/log/lastlog
        format: 'tar'
        dest: /root/files.tar

    - name: create bz2 archive
      archive:
        src: /root/files.tar
        format: 'bz2'
        dest: /root/files.tar.bz2
        remove: true

# nginx.yml
---
- hosts: web1
  become: true
  tasks:
    - name: Install nginx
      yum:
        name: nginx
        state: present
    
    - name: Start nginx
      service:
        name: nginx
        state: started
        enabled: yes
    
    - name: Extract nginx.zip
      unarchive:
        src: /root/nginx.zip
        dest: /usr/share/nginx/html
        remote_src: yes
    
    - name: Change Line in File
      replace:
        path: /usr/share/nginx/html/index.html
        regexp: '^This is sample html code'
        replace: 'This is KodeKloud Ansible lab'